export const heading = [
  { name: "Name", width: "232px", marginRight: "54px" },
  { name: "Email", width: "210px", marginRight: "24px" },
  { name: "Company Name", width: "120px", marginRight: "29px" },
  { name: "Mobile", width: "120px", marginRight: "19px" },
  { name: "Amount Due", width: "84px", marginRight: "34px" },
  { name: "Last Session", width: "130px", marginRight: "0px" },
];
export const sampleData = [
  {
    name: "Lindsey Stroud",
    email: "lindsey.stroud@gmail.com",
    companyName: "Hatchbuck",
    mobile: "+971 500000000",
    amountDue: "0 AED",
    lastSession: "5 Minutes ago",
  },
  {
    name: "Nicci Troiani",
    email: "nicci.troiani@gmail.com",
    companyName: "Slack",
    mobile: "+971 500000000",
    amountDue: "450 AED",
    lastSession: "14 Minutes ago",
  },
  {
    name: "Lindsey Stroud",
    email: "lindsey.stroud@gmail.com",
    companyName: "Hatchbuck",
    mobile: "+971 500000000",
    amountDue: "0 AED",
    lastSession: "5 Minutes ago",
  },
  {
    name: "Lindsey Stroud",
    email: "lindsey.stroud@gmail.com",
    companyName: "Hatchbuck",
    mobile: "+971 500000000",
    amountDue: "0 AED",
    lastSession: "5 Minutes ago",
  },
  {
    name: "Nicci Troiani",
    email: "nicci.troiani@gmail.com",
    companyName: "Slack",
    mobile: "+971 500000000",
    amountDue: "450 AED",
    lastSession: "14 Minutes ago",
  },
  {
    name: "Lindsey Stroud",
    email: "lindsey.stroud@gmail.com",
    companyName: "Hatchbuck",
    mobile: "+971 500000000",
    amountDue: "0 AED",
    lastSession: "5 Minutes ago",
  },
  {
    name: "Lindsey Stroud",
    email: "lindsey.stroud@gmail.com",
    companyName: "Hatchbuck",
    mobile: "+971 500000000",
    amountDue: "0 AED",
    lastSession: "5 Minutes ago",
  },
  {
    name: "Nicci Troiani",
    email: "nicci.troiani@gmail.com",
    companyName: "Slack",
    mobile: "+971 500000000",
    amountDue: "450 AED",
    lastSession: "14 Minutes ago",
  },
  {
    name: "Lindsey Stroud",
    email: "lindsey.stroud@gmail.com",
    companyName: "Hatchbuck",
    mobile: "+971 500000000",
    amountDue: "0 AED",
    lastSession: "5 Minutes ago",
  },
  {
    name: "Nicci Troiani",
    email: "nicci.troiani@gmail.com",
    companyName: "Slack",
    mobile: "+971 500000000",
    amountDue: "450 AED",
    lastSession: "14 Minutes ago",
  },
];
